name: build app and deploy to gh pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: setup pages
        uses: actions/configure-pages@v3

      - name: build app
        run: |
          npm i
          npm run build
        
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
          
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v2
