name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Vite Github Pages Deployer
      uses: skywarth/vite-github-pages-deployer@v1.2.0
